WebKitBrowser/cmake/FindWPEWebKit.cmake

Add `wpe-webkit-1.1` as usable pkg-config module. This corresponds to recent WPE WebKit versions built with soup3. While at it, switch over to `pkg_search_module()` which will pick the first module found from the list passed to it.

FindWPEWebKit.cmake: Allow picking WebKit 2.38 with soup3

---

WebKitBrowser/WebKitBrowser.cpp

Fixing the issue where this TRACE (https://github.com/rdkcentral/Thunder/blob/master/Source/core/Sync.h#L77) from Sync.h was constantly showing up, because the Unlock() method was called without a Lock() before that.

[WebKitBrowser] Adding two missing Locks

---

.github/workflows/Build ThunderNanoServicesRDK on Windows.yml

It was being built here in ThunderNanoServicesRDK as well as in ThunderNanoServices by mistake.

[Actions] Not building NetworkControl plugin on Windows

---

LocationSync/LocationSync.cpp
MessageControl/MessageControl.cpp
MessageControl/MessageControl.h
MessageControl/MessageOutput.cpp

It requires this PR to Thunder to be merged first: https://github.com/rdkcentral/Thunder/pull/1415

[Messaging] Adding a functionality to the MessageControl plugin to handle redirected standard out and error

---

.github/workflows/Build ThunderNanoServicesRDK on Linux.yml
.github/workflows/Linux build template.yml

Same as with the Thunder PR: https://github.com/rdkcentral/Thunder/pull/1496
This is an initial pull request - the new workflows have to be called from my branches for now (there is a dependency between the workflows), since we need to first merge new templates in each repo. Then, I'll make one more set of pull requests to redirect this new feature to master branches of our repos.
In this repo it was possible to change the required checks, and this is already done.

[Actions] Managing dependencies to make the workflows callable from different repos

---

.github/workflows/Build ThunderNanoServicesRDK on Linux.yml

The last set of pull requests, now the new Actions will use workflows from our repos instead of my forks, which sadly couldn't have been done in one go.

[Actions] Using the already merged workflows instead of my forks

---

MessageControl/MessageControl.h
MessageControl/MessageOutput.cpp
MessageControl/MessageOutput.h
WebKitBrowser/BrowserConsoleLog.h

This PR has to be merged first: https://github.com/rdkcentral/Thunder/pull/1548

[MessageControl] Updating MessageControl to match the new message buffers size changes

---

MessageControl/MessageControl.cpp
MessageControl/MessageOutput.cpp
MessageControl/MessageOutput.h

Like we discussed on Teams with @sebaszm, there are two major changes:
1. Making sure that UDP output uses the `Convert()` as all other Publishers, since it has not been updated up to this point
2. Allowing to store more than just one message in the `_sendBuffer`, since the `Trigger()` call is asynchronous. With Thunder already running, the `SendData()` method is called on average once every 1-3 calls of the Output() method, but when the framework starts, it can take quite a while before the first buffer "flush" happens (hence 4KB size, since I was still getting an ASSERT with 2KB)

[MessageControl] Fixing UDP output and allowing it to store more than one message

---

MessageControl/MessageControl.cpp
MessageControl/MessageOutput.cpp
MessageControl/MessageOutput.h

The idea of adding this functionality was mentioned in [this](https://jira.rdkcentral.com/jira/browse/METROL-1049) Jira ticket.

[MessageControl] Open a socket in UDPOutput only when Network is active

---

.github/workflows/Build ThunderNanoServicesRDK on MacOS.yml
.github/workflows/MacOS build template.yml
MessageControl/MessageControl.h
MessageControl/MessageOutput.h
Monitor/Monitor.h
OpenCDMi/CMakeLists.txt
OpenCDMi/FrameworkRPC.cpp
OpenCDMi/Protobuf.h
PerformanceMetrics/PerformanceMetrics.h
PerformanceMetrics/TraceOutput.cpp

@sebaszm are the unused member variables in `OpenCDMi/FrameworkRPC.cpp` necessary for anything, or can we get rid of them completely?

[Actions] Adding a MacOS build workflow, fixing several MacOS specific compilation errors and warnings

---

.github/workflows/Build ThunderNanoServicesRDK on MacOS.yml

Otherwise it clashes with the Linux required checks, even despite the workflow name being different

[Actions] Make sure all MacOS job names are unique

---

OpenCDMi/FrameworkRPC.cpp

@HaseenaSainul discovered that the `VARIABLE_IS_NOT_USED` leads to the build error with buildroot:
```
FrameworkRPC.cpp:383:69: error: ‘unused’ attribute ignored [-Werror=attributes]
383 |                     VARIABLE_IS_NOT_USED CDMi::IMediaKeySessionExt* _mediaKeysExt;
|                                                                     ^~~~~~~~~~~~~
FrameworkRPC.cpp:384:51: error: ‘unused’ attribute ignored [-Werror=attributes]
384 |                     VARIABLE_IS_NOT_USED uint8_t* _sessionKey;
|                                                   ^~~~~~~~~~~
FrameworkRPC.cpp:385:51: error: ‘unused’ attribute ignored [-Werror=attributes]
385 |                     VARIABLE_IS_NOT_USED uint32_t _sessionKeyLength;
|                                                   ^~~~~~~~~~~~~~~~~ …
```

[OpenCDMi] Remove all unnecessary member variables to save some memory

---

Monitor/Monitor.h

Add comments to explain why no locking is necessary in the MonitorObjects

Add comments to explain why no locking is necessary

---

SecurityAgent/SecurityAgent.h

Fix testmode token as a previous change broke it from what is was (no clue why it was changed).
As we take the sizeof later on the result, sizeof(char*) gives a completely different answer (incorrect of course) than sizeof(char[])

[SecAgent] fix test mode token

---

Packager/Packager.cpp
Packager/Packager.h
Packager/PackagerImplementation.cpp
Packager/PackagerImplementation.h
Packager/PackagerPlugin.json
Packager/doc/PackagerPlugin.md

First, we have to merge [this](https://github.com/rdkcentral/ThunderInterfaces/pull/412) PR with changes to the interface
Packager is not building in Lithosphere by default, and trying to build it leads to a CMake error:
```
CMake Error in Packager/CMakeLists.txt:
Imported target "LibOPKG::LibOPKG" includes non-existent path
"/home/veith/Lithosphere/raspberrypi3_wpe/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libopkg"
in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
* The path was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and references files it does not
provide.
```
After manually moving `libopkg` to this location, as it was installed in `usr/lib` …

[Packager] Update after changes to the interface

---

WebKitBrowser/WebKitImplementation.cpp

Amazon Luna can get  stuck on the loading screen if there's anything under `window.webkit`, which is the case when we register this handler in the page content world under `window.webkit.messageHandlers.wpeNotifyWPEFramework.postMessage()`.
See https://commits.webkit.org/281898@main for more information.

WebKitBrowser: fix Amazon Luna getting stuck on loading screen

---

.github/workflows/Build ThunderNanoServicesRDK on Linux.yml
.github/workflows/Linux build template.yml

Building Packager requires us to also manually build `libopkg` (which was quite challenging to get right on the runner), as it is not available as a package to be installed, but nonetheless it takes relatively short amount of time, and now we won't have a situation of _someone_ breaking Packager without realizing it 😄

[Actions] Build Packager on Linux with its dependencies (32- and 64-bit)

---

.github/workflows/Build ThunderNanoServicesRDK on Linux.yml
.github/workflows/Linux build template.yml
PlayerInfo/GStreamer/PlatformImplementation.cpp

This was the compile error from PlayerInfo:
```
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp:61:17: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
61 |                 if (elements = std::move(GstUtils::GstRegistryGetElementForMediaType(decoderFactories.get(), std::move(mediaType)))) {
|                 ^~
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp:64:24: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
64 |                 } else if (elements = std::move(GstUtils::GstRegistryGetElementForMediaType(parserFactories.get(), …
```

[PlayerInfo][Actions] Fixing a compile error, installing a package suddenly missing on the runner

---

WebKitBrowser/WebKitBrowser.cpp

Necessary to get rid of deprecated warnings treated as errors after [this](https://github.com/rdkcentral/Thunder/pull/1865) PR to Thunder
Also, the `static_assert` is no longer needed, since `IProcessMemory::ID` is now `pid_t`, which could be bigger than `uint32_t` on 64-bit architecture

[WebKitBrowser] Replace process_t with pid_t

---

Monitor/Monitor.h

Plugin is already marked as inactive in deactivated. So not doing the same in deinitialized

Already marked plugin as inactive in deactivated.
